### PR TITLE
Add ability to compare agains specified branch

### PR DESCRIPTION
**Pull request by jonnycaley**
Adds the ability to compare against a specified branch (addressing [this issue](https://github.com/dropbox/AffectedModuleDetector/issues/4))

### CODE REVIEW

**Comment by jonnycaley** [comment]
@digitalbuddha are you able to review when you have some spare time? 😄

**Comment by digitalbuddha** [comment]
Will try to review tomorrow. Waiting for things to get less hectic

**Comment by digitalbuddha** [comment]
Cc @chris-mitchell

**Review by digitalbuddha — APPROVED** [review]

**Comment by digitalbuddha** [comment]
Thank you for the addition! Please let me know if it works as expected within the snapshot and then I'll release. Snapshot should be posted once Travis finishes the merge commit deploy

**Comment by jonnycaley** [comment]
Yep! Tested using snapshot, good to go

**Comment by digitalbuddha** [comment]
0.1.1 is live. Enjoy!

**Pull request merged**
