### PR TITLE
Fix README typo's

### PR DESCRIPTION
**Pull request by blundell**
Just some small tweaks as I was reading through.

### CODE REVIEW

**Comment by blundell** [comment]
@digitalbuddha can you vouch for me ;-)

**Comment by digitalbuddha** [comment]
Sorry not a maintainer anymore @rharter is

**Review by rharter — APPROVED** [review]

**Comment by rharter** [comment]
Looks great, thanks, dude!

**Comment by blundell** [comment]
👋  np! good to e-see you :-)

**Pull request merged**
